[manager]
show_hidden = true

sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true

linemode = "none"
show_symlink = true

[preview]

tab_size = 2
max_width = 600
max_height = 900

[opener]
edit = [
    { run = 'nvim "$@"', desc = "Edit with Neovim", block = true, for = "unix" },
]

[open]
rules = [
    { name = "*/", use = [ "edit", "open", "reveal" ] },
    { mime = "text/*", use = [ "edit", "reveal" ] },
    { mime = "application/json", use = [ "edit", "reveal" ] },
    { mime = "*/javascript", use = [ "edit", "reveal" ] },
    { mime = "*/x-wine-extension-ini", use = [ "edit", "reveal" ] },
]

[which]

[input]

[confirm]

[select]

[tasks]

[plugin]
